easy_admin:
   entities:
        Volume:
            class: App\Entity\Volume
            disabled_actions: ['delete']
            list:
                actions: ['show']
                fields: ['id', 'email', 'size', 'apikey', 'files', 'updateDate', 'createDate']
        File:
            class: App\Entity\File
            disabled_actions: ['new', 'delete']
            list:
                actions: ['show']
                fields: ['id', 'name', 'size', 'mimeType', 'volume', 'createDate']
