easy_admin:
    site_name: CloudFile
    entities:
        Config:
            class: App\Entity\Config
            disabled_actions: ['new', 'delete']
            list:
                actions: ['show']
        Disk:
            class: App\Entity\Disk
            list:
                actions: ['show']
        Volume:
            class: App\Entity\Volume
            list:
                actions: ['show']
                fields: ['id', 'size', 'apikey', 'files', 'private', 'updateDate', 'online']
        File:
            class: App\Entity\File
            disabled_actions: ['new']
            list:
                actions: ['show']
                fields: ['id', 'name', 'size', 'mimeType', 'private', 'createDate']

